### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by asn007** [ozum/pg-generator#32] opened 2016-10-04 08:43 UTC
Hello! I am trying to generate model definitions, but when I execute command I face following error:

```
error: Template render error: (C:\Users\asn007\WebstormProjects\mercury\generator\db\relation-cheatsheet.txt.nunj.html) [Line 5, Column 10]
  Template render error: (C:\Users\asn007\WebstormProjects\mercury\generator\db\relation-cheatsheet.txt.nunj.html)
  TypeError: Cannot read property 'name' of null
    at Object.exports.prettifyError (C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\node_modules\nunjucks\src\lib.js:34:15)
    at C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\node_modules\nunjucks\src\environment.js:486:31
    at root [as rootRenderFunc] (eval at <anonymous> (C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\node_modules\nunjucks\src\environment.js:565:24), <anonymous>:224:3)
    at Obj.extend.render (C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\node_modules\nunjucks\src\environment.js:479:15)
    at C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\lib\index.js:119:58
    at PGGenerator._write.Promise [as _write] (C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\lib\index.js:106:12)
    at Walker.<anonymous> (C:\Users\asn007\AppData\Roaming\npm\node_modules\pg-generator\lib\index.js:193:52)
    at emitNone (events.js:67:13)
    at Walker.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:419:10)
```

DDL is

```
CREATE TABLE administrators
(
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR NOT NULL,
    last_login TIMESTAMPTZ DEFAULT now() NOT NULL,
    role INT DEFAULT 0,
    last_login_ip VARCHAR(255)
);
CREATE TABLE backcalls
(
    id SERIAL PRIMARY KEY NOT NULL,
    phone VARCHAR(255),
    created TIMESTAMPTZ DEFAULT now(),
    resolved BOOL DEFAULT false
);
CREATE TABLE carts
(
    id SERIAL PRIMARY KEY NOT NULL,
    created TIMESTAMPTZ DEFAULT now(),
    session VARCHAR
);
CREATE TABLE carts_custom_pizzas
(
    cart_id INT PRIMARY KEY NOT NULL,
    custom_pizza_id INT
);
CREATE TABLE carts_products
(
    cart_id INT,
    product_id INT,
    id SERIAL PRIMARY KEY NOT NULL,
    quantity INT DEFAULT 0
);
CREATE TABLE carts_products_modifiers
(
    cart_product_id INT,
    product_modifier_price_id INT
);
CREATE TABLE categories
(
    id SERIAL PRIMARY KEY NOT NULL,
    slug VARCHAR(255),
    name VARCHAR(255),
    image VARCHAR
);
CREATE TABLE categories_modifiers
(
    id SERIAL PRIMARY KEY NOT NULL,
    category_id INT,
    name VARCHAR(255)
);
CREATE TABLE categories_modifiers_values
(
    id SERIAL PRIMARY KEY NOT NULL,
    category_modifier_id INT,
    value VARCHAR(255)
);
CREATE TABLE custom_pizzas
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255),
    votes INT DEFAULT 0
);
CREATE TABLE custom_pizzas_ingredients
(
    custom_pizza INT NOT NULL,
    ingredient INT NOT NULL,
    CONSTRAINT custom_pizzas_ingredients_custom_pizza_ingredient_pk PRIMARY KEY (custom_pizza, ingredient)
);
CREATE TABLE orders
(
    id SERIAL PRIMARY KEY NOT NULL,
    cart_id INT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    address VARCHAR,
    created TIMESTAMPTZ DEFAULT now(),
    confirmed TIMESTAMPTZ DEFAULT to_timestamp((0),
    delivered TIMESTAMPTZ DEFAULT to_timestamp((0)
);
CREATE TABLE pizza_ingredient_categories
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255),
    is_unique BOOL DEFAULT false,
    is_required BOOL DEFAULT false
);
CREATE TABLE pizza_ingredients
(
    id SERIAL PRIMARY KEY NOT NULL,
    category_id INT,
    name VARCHAR(255),
    image VARCHAR,
    price DOUBLE PRECISION DEFAULT 0,
    available BOOL DEFAULT true
);
CREATE TABLE product
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR,
    image VARCHAR,
    category_id INT,
    description VARCHAR
);
CREATE TABLE product_modifiers_prices
(
    id SERIAL PRIMARY KEY NOT NULL,
    product_id INT,
    category_modifier_value_id INT,
    price DOUBLE PRECISION
);
CREATE TABLE settings
(
    key VARCHAR(255) NOT NULL,
    value JSON
);
CREATE UNIQUE INDEX administrators_username_uindex ON administrators (username);
ALTER TABLE carts_custom_pizzas ADD FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE;
ALTER TABLE carts_custom_pizzas ADD FOREIGN KEY (custom_pizza_id) REFERENCES custom_pizzas (id) ON DELETE CASCADE;
ALTER TABLE carts_products ADD FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE;
ALTER TABLE carts_products ADD FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE;
ALTER TABLE carts_products_modifiers ADD FOREIGN KEY (cart_product_id) REFERENCES carts_products (id);
ALTER TABLE carts_products_modifiers ADD FOREIGN KEY (product_modifier_price_id) REFERENCES product_modifiers_prices (id);
ALTER TABLE categories_modifiers ADD FOREIGN KEY (category_id) REFERENCES categories (id);
ALTER TABLE categories_modifiers_values ADD FOREIGN KEY (category_modifier_id) REFERENCES categories_modifiers (id);
ALTER TABLE custom_pizzas_ingredients ADD FOREIGN KEY (custom_pizza) REFERENCES custom_pizzas (id);
ALTER TABLE custom_pizzas_ingredients ADD FOREIGN KEY (ingredient) REFERENCES pizza_ingredients (id);
ALTER TABLE orders ADD FOREIGN KEY (cart_id) REFERENCES carts (id);
ALTER TABLE pizza_ingredients ADD FOREIGN KEY (category_id) REFERENCES pizza_ingredient_categories (id);
ALTER TABLE product ADD FOREIGN KEY (category_id) REFERENCES categories (id);
ALTER TABLE product_modifiers_prices ADD FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE product_modifiers_prices ADD FOREIGN KEY (category_modifier_value_id) REFERENCES categories_modifiers_values (id);
CREATE UNIQUE INDEX settings_key_uindex ON settings (key);
```

Just a wild guess, is the problem related to some of my columns named "name"?

**Comment by ozum** [comment] 2016-10-04 20:39
Hi,

I'm abroad now. I'll check when I return. Meanwhile, if you could tell what command have you executed, then I will look into that. Please write step by step.

**Comment by ozum** [comment] 2016-10-25 09:11
Hi,

Your DDL has some minor errors on `orders` table. I removed extra paranthesis around `to_timestamp((0)` and created your database as `pizza`. After that I executed

- `sudo npm install -g pg-generator`
- `pgen template sequelize -t sequelize-template`
- `pgen exec sequelize-template --host localhost --port 5432 --user user --database pizza --schema public --target model --log info --extension nunj.html --indent 4`

without error.

Could you please describe step by step what commands did you use?

Below is relation-cheatsheet.txt:

```


Administrator
-------------


Backcall
--------


Cart
----
has many          carts_custom_pizzas                      as CustomPizzasCartIdFkeys 
has many          carts_products                           as ProductsCartIdFkeys 
has many          orders                                   as OrdersCartIdFkeys 
belongs to many   custom_pizzas                            as CartsCustomPizzaCustomPizzas 
belongs to many   product                                  as CartsProductProducts 


CartsCustomPizza
----------------
belongs to        carts                                    as Cart 
belongs to        custom_pizzas                            as CustomPizza 


CartsProduct
------------
has many          carts_products_modifiers                 as ModifiersCartProductIdFkeys 
belongs to        carts                                    as Cart 
belongs to        product                                  as Product 
belongs to many   product_modifiers_prices                 as CartsProductsModifierProductModifierPrices 


CartsProductsModifier
---------------------
belongs to        carts_products                           as CartProduct 
belongs to        product_modifiers_prices                 as ProductModifierPrice 


Category
--------
has many          categories_modifiers                     as ModifiersCategoryIdFkeys 
has many          product                                  as ProductCategoryIdFkeys 


CategoriesModifier
------------------
has many          categories_modifiers_values              as ValuesCategoryModifierIdFkeys 
belongs to        categories                               as Category 


CategoriesModifiersValue
------------------------
has many          product_modifiers_prices                 as ProductModifiersPricesCategoryModifierValueIdFkeys 
belongs to        categories_modifiers                     as CategoryModifier 
belongs to many   product                                  as ProductModifiersPriceProducts 


CustomPizza
-----------
has many          carts_custom_pizzas                      as CartsCustomPizzasCustomPizzaIdFkeys 
has many          custom_pizzas_ingredients                as IngredientsCustomPizzaFkeys 
belongs to many   carts                                    as CartsCustomPizzaCarts 
belongs to many   pizza_ingredients                        as CustomPizzasIngredientIngredients 


CustomPizzasIngredient
----------------------
belongs to        custom_pizzas                            as RelatedCustomPizza 
belongs to        pizza_ingredients                        as RelatedIngredient 


Order
-----
belongs to        carts                                    as Cart 


PizzaIngredientCategory
-----------------------
has many          pizza_ingredients                        as PizzaIngredientsCategoryIdFkeys 


PizzaIngredient
---------------
has many          custom_pizzas_ingredients                as CustomPizzasIngredientsIngredientFkeys 
belongs to        pizza_ingredient_categories              as Category 
belongs to many   custom_pizzas                            as CustomPizzasIngredientCustomPizzas 


Product
-------
has many          carts_products                           as CartsProductsProductIdFkeys 
has many          product_modifiers_prices                 as ModifiersPricesProductIdFkeys 
belongs to        categories                               as Category 
belongs to many   carts                                    as CartsProductCarts 
belongs to many   categories_modifiers_values              as ProductModifiersPriceCategoryModifierValues 


ProductModifiersPrice
---------------------
has many          carts_products_modifiers                 as CartsProductsModifiersProductModifierPriceIdFkeys 
belongs to        categories_modifiers_values              as CategoryModifierValue 
belongs to        product                                  as Product 
belongs to many   carts_products                           as CartsProductsModifierCartProducts 


Setting
-------
```

**Comment by ozum** [comment] 2016-11-16 11:42
Since I cannot reproduce it and there isn't any further info provided by reporter, I will close this case now. If you reproduce this error, please feel free to reopen this ticket.

Best,

**Closed by ozum** 2016-11-16 11:42 UTC
Labels: invalid
