### ISSUE TITLE
default value with empty string

### ISSUE THREAD

**Issue by benjaminroveri** [ozum/pg-generator#41] opened 2017-02-21 08:52 UTC
[Create a table in postgresql, with default value as empty string]
CREATE TABLE test.test
(
  something_as_text text NOT NULL DEFAULT ''::text,
  something_as_varchar character varying NOT NULL DEFAULT ''::character varying,
  something_as_int bigint NOT NULL DEFAULT 0
)
WITH (
  OIDS=FALSE
);

[Run pgen]
pgen template sequelize -t sequelize-template
pgen exec sequelize-template -d ###### -u ###### -p ###### -h localhost --port 5432 -s 'test' -t "./pg-generator-test"

[content of pg-generator-test/definition/test.js]
'use strict';

module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Test', {
        somethingAsText: {
            type: DataTypes.TEXT,
            field: 'something_as_text',
            allowNull: false,
            defaultValue: "'::tex"
        },
        somethingAsVarchar: {
            type: DataTypes.STRING,
            field: 'something_as_varchar',
            allowNull: false,
            defaultValue: "'::character varyin"
        },
        somethingAsInt: {
            type: DataTypes.BIGINT,
            field: 'something_as_int',
            allowNull: false
        }
    }, {
        schema: 'test',
        tableName: 'test',
        timestamps: false
    });
};

module.exports.initRelations = function() {
    delete module.exports.initRelations; // Destroy itself to prevent repeated calls.
    var model = require('../index');
    var Test = model.Test;

};

[here is the bug]
all default values are truncated:
> defaultValue: "'::tex"
> defaultValue: "'::character varyin"
querying INSERT INTO test.test (something_as_int) VALUES (1) work well,
but doing this with nodejs put '::tex or '::character varyin as default value

**Comment by ozum** [comment] 2017-02-21 14:35
Hello,

Bug is fixed.

Please upgrade `pg-generator` to latest version. Also during update please ensure that `pg-structure` version is also updated to 3.5.13. (Part of the problem is related to `pg-structure` library)

Empty strings, numbers and string "0" has similar problems. All are fixed now.

Thanks for the report.

Kind regards,

**Closed** 2017-02-21 14:35 UTC
